default:

  project_name: liechtenstein_p2020

  project_internal:
    twodii_internal: TRUE
    project_location_ext: C:/Users/clare/Desktop/ExternalTest
    data_location_ext: C:/Users/clare/Desktop/Git/pacta-data/2019Q4
